before_script:
  - apt-get update -qq && apt-get install -y -qq git
  - git submodule sync --recursive
  - git submodule update --init --recursive --remote

compile_pdf:
  image: tianon/latex
  script:
    - make demo
  artifacts:
    paths:
      - demo.pdf
      - demo.pdfpc


