before_script:
  - apt-get update -qq && apt-get install -y -qq git pandoc
  - git submodule sync --recursive
  - git submodule update --init --recursive --remote

buildPDF:
  image: tianon/latex
  script:
    - make demo
  artifacts:
    paths:
      - demo.pdf
      - demo.pdfpc
      - example.pdf
      - example.pdfpc


# Testweise mit den gängen Distributionen bauen um Inkompatibilitäten schnell
# erkennen zu können (wird nur im master-Zweig von i4/tex/i4neo-demo ausgeführt)

# Generische Regel für auf Debian basierende Distributionen
.debianoide:
  only:
    - master@i4/tex/i4neo-demo
  before_script:
    - ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update -qq && apt-get install -y -qq make git texlive-full latexmk pandoc
    - git submodule sync --recursive
    - git submodule update --init --recursive --remote
  script:
    - cat /etc/os-release
    - make demo
  artifacts:
    paths:
      - demo.pdf
      - demo.pdfpc
      - example.pdf
      - example.pdfpc

# Latest Ubuntu LTS Release
ubuntuLatest:
  extends: .debianoide
  image: ubuntu:latest

# Latest (rolling) Ubuntu Release
ubuntuRolling:
  extends: .debianoide
  image: ubuntu:rolling

debianStable:
  extends: .debianoide
  image: debian:stable

debianTesting:
  extends: .debianoide
  image: debian:testing

debianOldStable:
  extends: .debianoide
  image: debian:oldstable
