buildPDF:
  image: inf4/neo
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - make demo
  artifacts:
    paths:
      - demo.pdf
      - demo.pdfpc
      - example.pdf
      - example.pdfpc
